apiVersion: v1
kind: Pod
metadata:
  labels:
    run: gitlab-parser
  name: git-clone-pod
spec:
  containers:
  - image: nginx
    name: nginx-cont
    volumeMounts:
    - name: new-volume
      mountPath: /usr/share/
  initContainers:
  - image: alpine/git
    name: git
    command:
    - sh
    - -c
    - |
      # Clone the Git repository
      git clone https://github.com/Raghu0461/k8s-persistent-volumes.git /temp
    volumeMounts:
    - name: new-volume
      mountPath: /temp
      #readOnly: true
  volumes:
  - name: new-volume
    emptyDir: {}
